name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'

jobs:
  acc-tests:
    runs-on: self-hosted
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - name: e2e test
        run: |
          export ARM_SUBSCRIPTION_ID=$(curl -s -H Metadata:true "http://169.254.169.254/metadata/instance?api-version=2017-08-01" | jq -r '.compute | .subscriptionId')
          export ARM_TENANT_ID=$(az login --identity | jq -r '.[0] | .tenantId')
          docker run --rm --runtime=kata-runtime --cpus=2 --memory=1024m -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_USE_MSI=true -v $(pwd):/src -w /src testrunner.azurecr.io/testrunner/tfmodule-e2e-runner:alpine sh -c "PATH=$PATH:/go/bin:/usr/local/go/bin make e2e-test"
      - name: version upgrade test
        run: |
          docker run --rm --runtime=kata-runtime --cpus=2 --memory=1024m -e ARM_SUBSCRIPTION_ID -e ARM_TENANT_ID -e ARM_USE_MSI=true -v $(pwd):/src -w /src testrunner.azurecr.io/testrunner/tfmodule-e2e-runner:alpine sh -c "PATH=$PATH:/go/bin:/usr/local/go/bin make version-upgrade-test"