name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'

jobs:
  acc-tests:
    runs-on: self-hosted
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - run: |
          docker run --rm --runtime=runc -e ARM_USE_MSI=true -v $(pwd):/src -w /src testrunner.azurecr.io/testrunner/tfmodule-testrunner:latest sh -c "PATH=$PATH:/go/bin:/usr/local/go/bin make e2e-test"