---
name: Pre Pull Request Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'

jobs:
  prepr-check:
    runs-on: self-hosted
    container:
      image: testrunner.azurecr.io/testrunner/tfmodule-testrunner:latest
      options: --rm --runtime=kata-runtime
    steps:
      - uses: actions/checkout@v3
      - run: |
          export PATH=$PATH:/go/bin:/usr/local/go/bin
          make pr-check