---
name: Vendor Dependencies Check
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'

jobs:
  depscheck:
    runs-on: ubuntu-latest
    container:
      image: tfmodule-testrunner:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/go/bin:/usr/local/go/bin
          make pr-check
#315b54708a70d492773087139284db49