---
name: Pre Pull Request Check
on:
  pull_request_target:
    types: ['opened', 'synchronize']
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'

jobs:
  depscheck:
    runs-on: ubuntu-latest
    container:
      image: testrunner.azurecr.io/testrunner/tfmodule-testrunner:latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          export PATH=$PATH:/go/bin:/usr/local/go/bin
          make pr-check