name: Protect Workflow (Pull Request Cannot Touch Github Workflow)
on:
  pull_request:
    types: ['opened', 'synchronize']
    paths:
      - '.github/workflows/**'

jobs:
  prepr-check:
    runs-on: ubuntu-latest
    steps:
      - name: Try to fail
        run: exit 1
      - name: Print message if we don't fail
        run: echo Pull Request Should Not Touch Workflow Code